apiVersion: v1
kind: Service
metadata:
  labels:
    run: bedrock-service
  name: bedrock-service
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 19132
    protocol: UDP
    targetPort: 19132
  selector:
    run: bedrock-pod
  sessionAffinity: None
  type: LoadBalancer