{{- if not .Values.lifecycle.isInit -}}
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bedrock-pod
  name: bedrock-pod
spec:
  containers:
  - image: itzg/minecraft-bedrock-server
    name: bedrock-pod
    env:
    - name: EULA
      value: 'TRUE'
    - name: GAMEMODE
      value: 'creative'
    - name: OPS
      value: '{{ .Values.minecraft.ops }}'
    - name: ALLOW_LIST_USERS
      value: '{{ .Values.minecraft.allowlist }}'
    - name: WHITE_LIST_USERS
      value: '{{ .Values.minecraft.allowlist }}'
    volumeMounts:
    - mountPath: /data
      name: bedrock-pvc
      readOnly: false
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: bedrock-pvc
    persistentVolumeClaim:
      claimName: bedrock-pvc
{{- end -}}